version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: fact_sales
    columns:
      - name: InvoiceNo
        tests:
          - not_null
      - name: CustomerID
        tests:
          - not_null
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: quantity_sold
        tests:
          - not_null
