version: 2

sources:
  - name: ecommerce
    schema: bronze_layer
    tables:
      - name: sales
      - name: customers
      - name: products
  
  # - name: ecommerce_silver
  #   schema: bronze_layer_staging
  #   tables:
  #     # - name: cleaned_sales
  #     - name: dim_customers
  #     # - name: cleaned_products